### ISSUE TITLE
[조대협] 쿠버네티스 개념 이해(고급 컨트롤러) -3

### ISSUE THREAD

**Issue by seryang** [Develop-Study/kubernetes-study#3]
# 고급 컨트롤러
   - `일반 컨트롤러` 
       - 일반적인 워크로드에 대해 Pod을 관리
       - `RC (Replication Controller)` `RS (ReplicaSet)` `Deployment`
   - `고급 컨트롤러` 
     - 운영환경에서는 웹서버 외에 `DB, Batch, Daemon 서버`와 같은 **다양한 워크로드 모델**이 존재하는데, 이를 지원하기 위한 컨트롤러를 쿠버네티스에서 지원
     - `1) DaemonSet` `2) Job` `3) Cron Jobs` `4) StatefulSet`이 있음

## 1. DaemonSet
   - Pod이 각각의 노드에서 하나씩만 돌게하는 형태로 Pod을 관리하는 컨트롤러
   - ![image](https://user-images.githubusercontent.com/7028121/104126583-bd41a200-53a0-11eb-952c-9b95435195a0.png)
   - RC나 RS에 의해 관리되는 Pod은 여러 노드의 상황에 따라서 일반적으로 비균등 배포를 하지만, DS는 모든 노드에 균등하게 하나씩만 배포
      - 이런 형태의 워크로드는 서버의 **모니터링이나 로그 수집 용도**로 많이 사용
   - DS는 특정 노드에만 Pod를 배포할 수 있도록, Pod의 `node selector`를 이용해서 라벨 지정 (= 특정 노드를 선택)
## 2. Job
   - 워크로드 중, 배치가 한번 실행되고 끝나는 형태의 작업이 있을 수 있음
   - Job은 이러한 형태를 지원하는 컨트롤러
   - ![image](https://user-images.githubusercontent.com/7028121/104128365-88d2e380-53aa-11eb-8c9f-e228c932fc9a.png)
   - **Job에 의해 관리되는 Pod은 Job이 종료되면, Pod을 같이 종료**
   - Job을 정의할때는 `아래와 같이` 컨테이너 스펙 부분에 image 뿐 아니라, 컨테이너에서 Job을 수행하기 위한 커맨드(command) 를 같이 입력

 ```yml
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
```

- Job 컨트롤러에 의해서 실행된 Pod은 **위 command의 실행 결과에 따라서 Job이 실패한지 성공한지를 판단 `프로세스의 exit 코드로 판단`**
        - 결과가 실패라면,이 Job을 재 실행할지 또는 그냥 끝낼지를 설정에 따라서 결정
    - 만약 Job이 끝나기 전에 만약에 비정상적으로 종료된다면?
    -  ![image](https://user-images.githubusercontent.com/7028121/104128474-1adaec00-53ab-11eb-9bfe-27c81fa8b73a.png)
        - `특정 노드가 장애가 났다고 가정` 
             - RC/RS에 의해서 관리되고 있는 Pod은 자동으로 다른 노드에서 다시 자동으로 생성되서 시작
             - 컨트롤러에 의해 관리되고 있지 않은 Pod은 다시 다른 노드에서 기동되지 않고 사라짐
        - 그렇다면 Job 에 의해서 관리되는 Pod은?
            - 2가지 설정이 있음
               - 1. 장애시 다시 시작 `O`
               - 2. 장애시 다시 시작 `X`
                   - 작업의 상태가 보장되는것이 아니라, 다시 처음부터 작업이 재 시작되는 것이기 때문에 resume이 아닌 restart의 개념
                   - 단, 처음부터 작업을 시작하더라도 데이타가 겹치거나 문제가 없는 형태여야함
                   - ex) 배치 작업의 경우 같은 작업을 연속해서 여러번 수행할때 `=데이타가 클 경우 범위를 나눠서 작업하는 경우` 
                        1. 순차 실행
                           - 같은 Pod를 순차적으로, 여러번 실행할 수 있도록 설정 가능
                           - Job 설정에서 `completion`에 횟수를 주면, 같은 작업을 `completion` 횟수만큼 순차적으로 반복
                           - ![image](https://user-images.githubusercontent.com/7028121/104128582-d00da400-53ab-11eb-91e6-cd0357cab56c.png)
                        2. 병렬 실행
                          - Job설정에서 `parallelism` 에 동시 실행할 수 있는 Pod의 수를 주면, 지정된 수 만큼 Pod를 실행하여 `completion` 횟수를 병렬로 처리
                          - ![image](https://user-images.githubusercontent.com/7028121/104128740-9ab58600-53ac-11eb-8da7-55238e979e90.png) `completion이 5, parallelism이 2일때, 하나의 노드에서 모든 Pod가 실행된다고 가정했을때, 실행 순서`

## 4. Cron jobs
- 주기적으로 정해진 스케쥴에 따라 Job 컨트롤러에 의해 작업을 실행해주는 컨트롤러
- unix/linux cron 명령어처럼 시간에 따른 실행조건을 정의해 놓을 수 있음
- “schedule” 항목이 있으며 다른건 Job 컨트롤러 설정과 비슷

```yml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
```

## 5. StatefulSet
- 1.9에 정식으로 릴리즈됨
- RS/RC나 다른 컨트롤러로는 데이타베이스와 같이 상태를 가지는 애플리케이션을 관리하기가 어려움
- 상태를 가지고 있는 Pod를 지원하기 위해서 StatefulSet 이라는 것이 새로 소개됨
    - 이를 이해하기 위해서는 쿠버네티스의 디스크 볼륨에 대한 이해가 필요하여 이후 강의`쿠버네티스 #5 - 디스크 (볼륨/Volume)
`에서 확인

**출처: https://bcho.tistory.com/1257?category=731548 [조대협의 블로그]**
