### ISSUE TITLE
[조대협] 쿠버네티스 디스크 (볼륨/Volume) -5 

### ISSUE THREAD

**Issue by seryang** [Develop-Study/kubernetes-study#5]
# 쿠버네티스의 디스크 서비스인 볼륨이란?
- Pod에 종속된 디스크 
- 컨테이너 단위가 아니기때문에 Pod에 속해 있는 여러개의 컨테이너가 공유할 수 있음

# 볼륨 종류 
- 쿠버네티스의 볼륨은 여러가지 종류가 있음
- 로컬디스크뿐만 아니라 외장디스크, 퍼플릭 클라우드에서 제공되는 딧크, private 클라우드 솔루션에서 제공하는 디스크 볼륨 등 다양한 볼륨을 지원함
- 자세한 볼륨 리스트는  https://kubernetes.io/docs/concepts/storage/volumes/#types-of-volumes 참고
- 볼륨 타입을 구분해보면 크게 임시/로컬/네트워크 디스크 등으로 분류할 수 있음

Temp | Local | Network
-- | -- | --
emptyDir | hostPath | GlusterFS, gitRepo, NFS, iSCSI, gcePersistentDisk, AWS EBS, azureDisk, Fiber Channel, Secret, VshereVolume

## 1. 임시 디스크 (=emptyDir)
- emptyDir는 pod이 생성될때 같이 생성되고, pod이 삭제될때 같이 삭제되는 임시 볼륨
- Pod내의 컨테이너가 carsh되어 삭제되거나 재생성되어도, emptyDir의 생명주기는 Pod 단위이기 때문에 삭제되지 않고 계속 사용 가능
- 생성 당시 디스크에 아무 내용이 없기 때문에 emptyDir라 부름
- 물리적으로 노드에 할당해주는 디스크에 저장이 되는데 (각 환경에 따라 노드의 로컬 디스크가 될 수도 있고, 네트워크 디스크가 될수도 있음) emptyDir.medium 필드에 `Memory`라고 지정해주면, emptyDir의 내용은 물리 디스크 대신 메모리에 저장이 됨
- ex) 하나의 pod에 nginx와 redis 컨테이너를 기동시키고, emptyDir 볼륨을 생성하여 이를 공유하는 설정
```yml
apiVersion: v1
kind: Pod
metadata:
  name: shared-volumes 
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - name: shared-storage
      mountPath: /data/shared
  - name: nginx
    image: nginx
    volumeMounts:
    - name: shared-storage
      mountPath: /data/shared
  volumes:
  - name : shared-storage
    emptyDir: {}
```
- shared-storage라는 이름으로 emptyDir 기반의 볼륨을 만든 후에, nginx와 redis 컨테이너의 /data/shared 디렉토리에 마운트를 함
- Pod을 기동시킨후에 redis 컨테이너의 /data/shared 디렉톨에 들어가보면 아무 파일이 없다는 것을 확인할 수 이음
![image](https://user-images.githubusercontent.com/7028121/114201131-d69ebe00-9990-11eb-9ab6-b5ec96a19cea.png)
- 이 상태에서 아래와 같이 file.txt 파일을 생성하고
- ![image](https://user-images.githubusercontent.com/7028121/114201176-e3231680-9990-11eb-8369-21cf4bd92150.png)
- 다음 nginx 컨테이너로 들어가서 /data/shared 디렉토리를 살펴보면 file.txt 파일이 있는 것을 확인할 수 있음
- ![image](https://user-images.githubusercontent.com/7028121/114201259-f33af600-9990-11eb-8378-0d127f6a37b9.png)
- 이 파일은 redis 컨테이너에서 생성되었지만, nginx 컨테이너에서도 접근이 가능하게 됨

## 2. 로컬 디스크  (=hostPath)
- hostPath는 노드의 로컬 디스크의 경로를 Pod에서 마운트해서 사용
- 같은 hostPath에 있는 볼륨은 여러 Pod 사이에서 공유되어 사용됨
- Pod이 삭제되더라도 hostPath에 있는 파일들은 삭제되지 않고, 다른 pod이 hostPath를 마운트하게 되면, 남아 있는 파일을 액세스할 수 있음
- ![image](https://user-images.githubusercontent.com/7028121/114201572-50cf4280-9991-11eb-80c7-08419ff399c7.png)
- 주의할 점이 있다면 pod이 재시작되어 다른 노드에서 기동될 경우, 그 노드의 hostPath를 사용하기 때문에 이전에 다른 노드에서 사용한 hostPath의 파일 내용은 액세스가 불가능
- hostPaTh는 노드의 파일 시스템을 접근하는데 유용함
- 예를 들면, 노드의 로그 파일을 읽어서 수집하는 로그 agent를 pod로 배포했을 경우, 이 pod에서 노드의 파일 시스템을 접근해야 할때 유용하게 사용할 수 있음
- ex) 노드의 /tmp 디렉토리를 hostPath를 이용하여 /data/shared 디렉토리에 마운트
```yml
apiVersion: v1
kind: Pod
metadata:
  name: hostpath
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - name: terrypath
      mountPath: /data/shared
  volumes:
  - name : terrypath
    hostPath:
      path: /tmp
      type: Directory
```
- 이 pod을 배포해서 pod의 id를 얻어봄
- ![image](https://user-images.githubusercontent.com/7028121/114201988-b91e2400-9991-11eb-8ec3-4a054b005bdf.png)
- pod id를 통해서 vm을 아래와 같이 확인
- ![image](https://user-images.githubusercontent.com/7028121/114202039-c804d680-9991-11eb-9848-c15a7911adf8.png)
- vm에 ssh로 접속해서 /tmp/에  hello.txt 파일을 생성
- ![image](https://user-images.githubusercontent.com/7028121/114202093-d4892f00-9991-11eb-93eb-e5dd58cb56ec.png)
- 그 다음 pod의 컨테이너에 마운트된 /data/shared 디렉토리를 확인해보면 아래와 같이 노드의 /tmp 디렉토리의 내용이 그대로 보이는 것을 확인할 수 있음
- ![image](https://user-images.githubusercontent.com/7028121/114202207-ebc81c80-9991-11eb-86c5-89c53f8627bb.png)

### 1. gitRepo
- 생성시에 지정된 git repo의 특정 리비전의 내용을 clone하여 디스크 볼륨을 생성하는 방식
- 물리적으로 emptyDir이 생성되고, git repo의 내용은 closne으로 다운 받음
- ![image](https://user-images.githubusercontent.com/7028121/114204509-3e0a3d00-9994-11eb-8a07-6af10d2b5713.png)
- HTML과 같은 정적 파일이나 ruby on rails, php, node.js와 같은 스크립트 언어의 코드들은 gitRepo 볼륨을 이용하여 손쉽게 배포가 가능
```yml
apiVersion: v1
kind: Pod
metadata:
 name: gitrepo-volume-pod
spec:
 containers:
 - image: nginx:alpine
   name: web-server
   volumeMounts:
   - name: html
     mountPath: /usr/share/nginx/html
     readOnly: true
   ports:
   - containerPort: 80
     protocol: TCP
 volumes:
 - name: html
   gitRepo:
        repository: https://github.com/luksa/kubia-website-example.git
        revision: master
        directory: .
```
 - 이 설정  https://github.com/luksa/kubia-website-example.git 의 master 리비전을 클론으로 다운받아서 /usr/share/nginx/html에 마운트 시키는 설정

### 2. PersistentVolume and PersistentVolumeClaim
- 일반적으로 디스크 볼륨을 설정하려면 물리적 디스크를 생성해야 하고, 이러한 물리적 디스크에 대한 설정을 자세하게 이해할 필요가 있음
- 쿠버네티스는 인프라에 대한 복잡성을 추상화(간단하게) 하고, 개발자들이 손쉽게 필요한 인프라 (컨테이너,디스크, 네트워크)를 설정할 수 있도록 하는 개념을 가지고 있음
- 그래서 인프라에 종속적인 부분은 시스템 관리자가 설정하도록 하고, 개발자는 이에 대한 이해 없이 간단하게 사용할 수 있도록 디스크 볼륨 부분에 `PersistentVolumeClaim` (이하 PVC)와 `PersistentVolume` (이하 PV)라는 개념을 도입
- 시스템 관리자가 실제 물리 디스크를 생성한 후에, 이 디스크를 PersistentVolume이라는 이름으로 쿠버네티스에 등록
- 개발자는 Pod을 생성할때, 볼륨을 정의하고, 이 볼륨 정의 부분에 물리적 디스크에 대한 특성을 정의하는 것이 아니라 **PVC를 지정하여, 관리자가 생성한 PV와 연결**한다.
- 그림으로 정리해보면 다음과 같다. 
![image](https://user-images.githubusercontent.com/7028121/114204882-a9540f00-9994-11eb-9d03-f35d4f45126f.png)
- 시스템 관리자가 생성한 물리 디스크를 쿠버네티스 클러스터에 표현한것이 PV이고, Pod의 볼륨과 이 PV를 연결하는 관계가 PVC가 됨
- 주의할 점은 볼륨은 생성된 후에 직접 삭제하지 않는 한 절대 삭제되지 않음
-  PV의 생명 주기는 쿠버네티스 클러스터에 의해서 관리됨 
- Pod의 생성 또는 삭제에 상관없이 별도로 관리 (Pod와 상관없이 직접 생성하고 삭제함)

>PersistentVolume
- PV는 물리 디스크를 쿠버네티스에 정의한 예제로, NFS 파일 시스템 5G를 pv0003이라는 이름으로 정의 
- ![image](https://user-images.githubusercontent.com/7028121/114204868-a5c08800-9994-11eb-921b-a78ff4b17c75.png)
- PV를 설정하는데 여러가지 설정 옵션이 있는데, 간략하게 그 내용을 살펴보면 다음과 같다.
  - Capacity : 볼륨의 용량을 정의한다. 현재는 storage 항목을 통해서 용량만을 지정하는데 향후에는 필요한 IOPS나 Throughput등을 지원할 예정이다. 
  - VolumeMode : VolumeMode는 Filesystem (default)또는 raw를 설정할 수 있는데, 볼륨이 일반 파일 시스템인데, raw 볼륨인지를 정의한다.
   - Reclaim Policy : PV는 연결된 PVC가 삭제된 후 다시 다른 PVC에 의해서 재 사용이 가능한데, 재 사용시에 디스크의 내용을 지울지 유지할지에 대한 정책을 Reclaim Policy를 이용하여 설정이 가능하다. 
      - Retain : 삭제하지 않고 PV의 내용을 유지한다.
      - Recycle : 재 사용이 가능하며, 재 사용시에는 데이타의 내용을 자동으로 rm -rf 로 삭제한 후 재사용이 된다.
      - Delete : 볼륨의 사용이 끝나면, 해당 볼륨은 삭제 된다. AWS EBS, GCE PD,Azure Disk등이 이에 해당한다. 
      - Reclaim Policy은 모든 디스크에 적용이 가능한것이 아니라, 디스크의 특성에 따라서 적용이 가능한 Policy가 있고, 적용이 불가능한 Policy 가 있다. 
   - AccessMode : AccessMode는 PV에 대한 동시에 Pod에서 접근할 수 있는 정책을 정의한다. 
      - ReadWriteOnce (RWO) : 해당 PV는 하나의 Pod에만 마운트되고 하나의 Pod에서만 읽고 쓰기가 가능하다.
      - ReadOnlyMany(ROX) : 여러개의 Pod에 마운트가 가능하며, 여러개의 Pod에서 동시에 읽기가 가능하다. 쓰기는 불가능하다. 
      - ReadWriteMany(RWX) : 여러개의 Pod에 마운트가 가능하고, 동시에 여러개의 Pod에서 읽기와 쓰기가 가능하다. 
      - 위와 같이 여러개의 모드가 있지만, 모든 디스크에 사용이 가능한것은 아니고 디스크의 특성에 따라서 선택적으로 지원된다. 

> PV의 라이프싸이클
- PV는 생성이 되면, Available 상태가 된다. 이 상태에서 PVC에 바인딩이 되면 Bound 상태로 바뀌고 사용이 되며, 바인딩된 PVC가 삭제 되면, PV가 삭제되는 것이 아니라  Released 상태가 된다.  (Available이 아니면 사용은 불가능하고 보관 상태가 된다.)

> PV 생성 (Provisioning)
- PV의 생성은 앞에서 봤던것 처럼 yaml 파일등을 이용하여, 수동으로 생성을 할 수 도 있지만, 설정에 따라서 필요시마다 자동으로 생성할 수 있게 할 수 있다. 이를 Dynamic Provisioning (동적 생성)이라고 하는데, 이에 대해서는 PVC를 설명하면서 같이 설명하도록 하겠다. 

> PersistentVolumeClaim
- PVC는 Pod의 볼륨과 PVC를 연결(바인딩/Bind)하는 관계 선언이다. 
- 아래 예제를 보자 아래 예제는 PVC의 예제이다. 
- ![image](https://user-images.githubusercontent.com/7028121/114204829-99d4c600-9994-11eb-9119-e75d720162d2.png)
- (출처 : https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims)
- accessMode, VolumeMode는 PV와 동일하다. 
- resources는 PV와 같이, 필요한 볼륨의 사이즈를 정의한다.
- selector를 통해서 볼륨을 선택할 수 있는데, label selector 방식으로 이미 생성되어 있는 PV 중에, label이 매칭되는 볼륨을 찾아서 연결하게 된다. 

> PV/PVC 예제
- 그러면 예제를 통해서 PV를 생성하고, 이 PV를 PVC에 연결한후에, PVC를 Pod에 할당하여 사용하는 방법을 살펴보도록 하자. 예제는 구글 클라우드 환경을 사용하였다.

1.물리 디스크 생성
- 먼저 구글 클라우드 콘솔에서 Compute Engine 부분에서 아래와 같이 Disks 부분에서 물리 디스크를 생성한다.
- ![image](https://user-images.githubusercontent.com/7028121/114207209-1799d100-9997-11eb-9de4-4f69fa583074.png)
- 디스크를 pv-demo-disk라는 이름으로 생성하였다. 
- 이때 주의할점은 디스크의 region과 zone이 쿠베네티스 클러스터가 배포된 region과 zone에 동일해야 한다. 

2.생성된 디스크로 PV를 선언 
- 생성된 디스크를 이용하여 PV를 생성한다. 아래는 PV를 생성하기 위한 yaml 파일이다. 
```yml
existing-pd.yaml

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-demo
spec:
  storageClassName:
  capacity:
    storage: 20G
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: pv-demo-disk
    fsType: ext4
```
- PV의 이름은 pv-demo이고, gcePersistentDisk에서 앞에서 생성한 pv-demo-disk 를 사용하도록 정의하였다. 
- 파일을 실행하면, 아래와 같이 pv-demo로 PV가 생성된것을 확인할 수 있다.
- ![image](https://user-images.githubusercontent.com/7028121/114207293-31d3af00-9997-11eb-9d2c-4d7ecf8ffc18.png)

3. 다음 PVC를 생성한다.
- 아래는 앞에서 생성한 pv-demo PV를 사용하는 PVC를 생성하는 yaml 파일이다. 하나의 Pod에서만 액세스가 가능하도록 accessMode를 ReadWriteOnce로 설정하였다.

```yml
existing-pvc.yaml

apiVersion: v1
kind : PersistentVolumeClaim
metadata:
  name: pv-claim-demo
spec:
  storageClassName: ""
  volumeName: pv-demo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20G
```

4. Pod를 생성하여, PVC를 바인딩
- 그러면 앞에서 생성한 PV와 PVC를 Pod에 생성해서 연결하자
```yml
existing-pod-redis.yaml

apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - name: terrypath
      mountPath: /data
  volumes:
  - name : terrypath
    persistentVolumeClaim:
      claimName: pv-claim-demo
```

- 앞에서 생성한 PVC pv-claim-demo를 Volume에 연결한후, 이 볼륨을 /data 디렉토리에 마운트 하였다.
- Pod를 생성한후에, 생성된 Pod에 df -k 로 디스크 연결 상태를 확인해 보면 다음과 같다.
- ![image](https://user-images.githubusercontent.com/7028121/114207099-f76a1200-9996-11eb-88ab-b5918b941a69.png)
- /dev/sdb 가 20G로 생성되어 /data 디렉토리에 마운트 된것을 확인할 수 있다. 

> Dynamic Provisioning
- 앞에서 본것과 같이 PV를 수동으로 생성한후 PVC에 바인딩 한 후에, Pod에서 사용할 수 있지만, 쿠버네티스 1.6에서 부터 Dynamic Provisioning (동적 생성) 기능을 지원한다. 이 동적 생성 기능은 시스템 관리자가 별도로 디스크를 생성하고 PV를 생성할 필요 없이 PVC만 정의하면 이에 맞는 물리 디스크 생성 및 PV 생성을 자동화해주는 기능이다. 
- ![image](https://user-images.githubusercontent.com/7028121/114206937-d1dd0880-9996-11eb-887f-f6d2862552b0.png)
- PVC를 정의하면, PVC의 내용에 따라서 쿠버네티스 클러스터가 물리 Disk를 생성하고, 이에 연결된 PV를 생성한다. 
- 실 환경에서는 성능에 따라 다양한 디스크(nVME, SSD, HDD, NFS 등)를 사용할 수 있다. 그래서 디스크를 생성할때, 필요한 디스크의 타입을 정의할 수 있는데, 이를 storageClass 라고 하고, PVC에서 storage class를 지정하면, 이에 맞는 디스크를 생성하도록 한다. 
- Storage class를 지정하지 않으면, 디폴트로 설정된 storage class 값을 사용하게 된다. 
- 동적 생성 방법은 어렵지 않다. PVC에 필요한 디스크 용량을 지정해놓으면, 자동으로 이에 해당하는 물리 디스크 및 PV가 생성이 된다. 아래는 동적으로 PV를 생성하는 PVC 예제이다. 
```yml
dynamic-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mydisk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
```
- 다음 Pod를 생성한다.
```yml
apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - name: terrypath
      mountPath: /data/shared
  volumes:
  - name : terrypath
    persistentVolumeClaim:
      claimName: mydisk
```
- Pod를 생성한후에, kubectl get pvc 명령어를 이용하여, 생성된 PVC와 PV를 확인할 수 있다. 
- ![image](https://user-images.githubusercontent.com/7028121/114207421-52036e00-9997-11eb-9804-49a81dac32d2.png)
- PVC는 위에서 정의한것과 같이 mydisk라는 이름으로 생성되었고, Volume (PV)는 pvc-4a…. 식으로 새롭게 생성되었다. 

> Storage class
- 아래는  AWS EBS 디스크에 대한 스토리지 클래스를 지정한 예로, slow 라는 이름으로 스토리지 클래스를 지정하였다. EBS 타입은 io1을 사용하고, GB당 IOPS는 10을 할당하도록 하였고, 존은 us-east-1d와 us-east-1c에 디스크를 생성하도록 하였다. 
- ![image](https://user-images.githubusercontent.com/7028121/114207460-5cbe0300-9997-11eb-9875-54af6f463c27.png)
- 아래는 구글 클라우드의 Persistent Disk (pd)의 예로, slow라는 이름으로 스토리지 클래스를 지정하고, pd-standard (HDD)타입으로 디스크를 생성하되 us-central1-a와 us-central1-b 존에 디스크를 생성하도록 하였다. 
- ![image](https://user-images.githubusercontent.com/7028121/114207485-62b3e400-9997-11eb-8414-c7b4e0a041d4.png)
- 이렇게 정의한 스토리지 클래스는  PVC 정의시에, storageClassName에 적으면 PVC에 연결이 되고, 스토리지 클래스에 정해진 스펙에 따라서 물리 디스크와 PV를 생성하게 된다. 

---

출처: https://bcho.tistory.com/1259?category=731548 [조대협의 블로그]
